# Install required plugins
required_plugins = ["vagrant-hostsupdater"]
required_plugins.each do |plugin|
    exec "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/bionic64"
	config.vm.network "private_network", ip: "192.168.10.100"
	config.hostsupdater.aliases = ["development.local"]

	# upload files to VM
	#config.vm.provision "file", source: "C:\\Users\\daiji\\Desktop\\sparta\\devops_devenvs\\task_provision\\starter-code\\app", destination: "$HOME/startercode/app"
	# config.vm.provision "file", source: "C:\\Users\\daiji\\Desktop\\sparta\\devops_devenvs\\task_provision\\starter-code\\environment", destination: "$HOME/startercode/environment"
	config.vm.synced_folder "environment/", "/startercode/environment"
	config.vm.synced_folder "app/", "/startercode/app"

	# run provision cript
	config.vm.provision "shell", path: "environment/provision.sh"


end